package com.dofus.persistence.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.ToString;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA Entity representing a Dofus Retro player/character.
 *
 * <p>This entity stores core player information including character name, level,
 * position, and relationships to inventory, stats, and combat sessions.
 *
 * <p>Key Features:
 * <ul>
 *   <li>One-to-One relationship with PlayerStats (eager loaded)</li>
 *   <li>One-to-Many relationship with InventoryItem (lazy loaded)</li>
 *   <li>One-to-Many relationship with CombatSession (lazy loaded)</li>
 *   <li>Automatic timestamp management via @PrePersist and @PreUpdate</li>
 * </ul>
 *
 * @author Agent A2 - Database Architect
 * @version 1.0
 * @since 2025-11-08
 */
@Entity
@Table(
    name = "players",
    indexes = {
        @Index(name = "idx_players_character_name", columnList = "character_name"),
        @Index(name = "idx_players_map_id", columnList = "map_id"),
        @Index(name = "idx_players_level", columnList = "level"),
        @Index(name = "idx_players_last_seen", columnList = "last_seen"),
        @Index(name = "idx_players_breed", columnList = "breed")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"inventoryItems", "combatSessions", "stats"}) // Avoid lazy loading in toString
@EqualsAndHashCode(of = {"id"}) // Only use ID for equals/hashCode
public class Player {

    /**
     * Unique player identifier (UUID format).
     * Generated by application, not database.
     */
    @Id
    @Column(name = "id", length = 36, nullable = false)
    private String id;

    /**
     * In-game character name (must be unique).
     * Used for player identification and lookup.
     */
    @Column(name = "character_name", nullable = false, unique = true, length = 100)
    private String characterName;

    /**
     * Character level (1-200 for Dofus Retro).
     * Defaults to level 1 for new characters.
     */
    @Column(name = "level", nullable = false)
    @Builder.Default
    private Integer level = 1;

    /**
     * Total experience points.
     * Used for level progression tracking.
     */
    @Column(name = "experience", nullable = false)
    @Builder.Default
    private Long experience = 0L;

    /**
     * Character breed/class.
     * Possible values: Iop, Sadida, Eniripsa, Enutrof, Sram, Xelor,
     * Ecaflip, Feca, Sacrieur, Cra, Osamodas, Pandawa.
     */
    @Column(name = "breed", length = 50)
    private String breed;

    /**
     * Current map ID where player is located.
     * References the maps table (soft reference, no FK constraint).
     */
    @Column(name = "map_id")
    private Integer mapId;

    /**
     * Current cell position on the map (0-559 for standard maps).
     * Represents tactical grid position.
     */
    @Column(name = "cell_id")
    private Integer cellId;

    /**
     * Timestamp of last player activity.
     * Updated on every packet received from this player.
     */
    @Column(name = "last_seen")
    private LocalDateTime lastSeen;

    /**
     * Record creation timestamp.
     * Automatically set on first insert.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Last record update timestamp.
     * Automatically updated on every modification.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // ========================================================================
    // RELATIONSHIPS
    // ========================================================================

    /**
     * Player's inventory items.
     * Lazy loaded to avoid performance issues.
     * Cascade ALL: deleting player deletes all inventory items.
     */
    @OneToMany(
        mappedBy = "player",
        fetch = FetchType.LAZY,
        cascade = CascadeType.ALL,
        orphanRemoval = true
    )
    @Builder.Default
    private List<InventoryItem> inventoryItems = new ArrayList<>();

    /**
     * Player's combat session history.
     * Lazy loaded for performance.
     * No cascade delete (keep combat history).
     */
    @OneToMany(
        mappedBy = "player",
        fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<CombatSession> combatSessions = new ArrayList<>();

    /**
     * Player statistics (HP, MP, AP, etc.).
     * One-to-One relationship, eager loaded as stats are frequently accessed.
     * Cascade ALL: player and stats lifecycle are tied together.
     */
    @OneToOne(
        mappedBy = "player",
        fetch = FetchType.EAGER,
        cascade = CascadeType.ALL,
        orphanRemoval = true
    )
    private PlayerStats stats;

    // ========================================================================
    // LIFECYCLE CALLBACKS
    // ========================================================================

    /**
     * Called before entity is persisted to database.
     * Initializes creation and update timestamps.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (createdAt == null) {
            createdAt = now;
        }
        if (updatedAt == null) {
            updatedAt = now;
        }
        if (lastSeen == null) {
            lastSeen = now;
        }
    }

    /**
     * Called before entity is updated in database.
     * Updates the updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ========================================================================
    // HELPER METHODS
    // ========================================================================

    /**
     * Updates player position (map and cell).
     *
     * @param newMapId new map identifier
     * @param newCellId new cell position
     */
    public void updatePosition(Integer newMapId, Integer newCellId) {
        this.mapId = newMapId;
        this.cellId = newCellId;
        this.lastSeen = LocalDateTime.now();
    }

    /**
     * Updates player level and experience.
     *
     * @param newLevel new character level
     * @param newExperience new experience total
     */
    public void updateLevelAndExperience(Integer newLevel, Long newExperience) {
        this.level = newLevel;
        this.experience = newExperience;
        this.lastSeen = LocalDateTime.now();
    }

    /**
     * Adds an item to player's inventory.
     * Maintains bidirectional relationship.
     *
     * @param item inventory item to add
     */
    public void addInventoryItem(InventoryItem item) {
        inventoryItems.add(item);
        item.setPlayer(this);
    }

    /**
     * Removes an item from player's inventory.
     * Maintains bidirectional relationship.
     *
     * @param item inventory item to remove
     */
    public void removeInventoryItem(InventoryItem item) {
        inventoryItems.remove(item);
        item.setPlayer(null);
    }

    /**
     * Adds a combat session to player's history.
     * Maintains bidirectional relationship.
     *
     * @param combatSession combat session to add
     */
    public void addCombatSession(CombatSession combatSession) {
        combatSessions.add(combatSession);
        combatSession.setPlayer(this);
    }

    /**
     * Sets player statistics.
     * Maintains bidirectional relationship.
     *
     * @param stats player stats entity
     */
    public void setStats(PlayerStats stats) {
        this.stats = stats;
        if (stats != null) {
            stats.setPlayer(this);
        }
    }

    /**
     * Checks if player is currently in combat.
     *
     * @return true if player has an ongoing combat session
     */
    public boolean isInCombat() {
        return combatSessions.stream()
            .anyMatch(session -> session.getEndTime() == null);
    }

    /**
     * Gets the number of items in inventory.
     *
     * @return inventory item count
     */
    public int getInventorySize() {
        return inventoryItems.size();
    }
}
