spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.dofus: DEBUG

dofus:
  network:
    proxy:
      enabled: false
  game:
    packet-logging: false
